### PR TITLE
PetFriendResolver v1.0.1 submit

### PR DESCRIPTION
**Pull request by jzafrap**
PetFriendResolver, tested over snowflake dashboard on Rinkeby network. PetFriendResolver contract address: 0x26098F10E1539a6b75998AfB1DA552B8fD0AE404.

### CODE REVIEW

**Comment by NoahHydro** [comment]
hey @jzafrap! can you fix the linting errors per the [output here](https://travis-ci.org/HydroBlockchain/snowflake-dashboard/builds/490194589?utm_source=github_status&utm_medium=notification)? You can also view them locally with `npm run lint`.

**Comment by NoahHydro** [comment]
Also, would you mind verifying your [source code here](https://rinkeby.etherscan.io/address/0x26098F10E1539a6b75998AfB1DA552B8fD0AE404#code)?

**Comment by NoahHydro** [comment]
Also one quick question, when I claimed to have found your pet it doesn't look like I received the payment..do you have to approve my claim for the payment to be sent?

**Comment by jzafrap** [comment]
Yes! Owner has to confirm. You'll see yellow icon until I confirm. Sorry,
I'm not in the pc, i can't do It Now. I Will send you an email When i do It.

**Comment by jzafrap** [comment]
Yes! I don't know you could do that! I'll do tomorrow, and send you a
confirm email.

**Comment by jzafrap** [comment]
Yes! But Hope deprecated uses don't make change js a lot! I Will confirm
When done.

**Comment by NoahHydro** [comment]
@jzafrap got it, makes sense. and sounds good, no rush!

**Comment by jzafrap** [comment]
I introduce current status:
1) source code of contract added to ethscan, you can review it!
2) I have confirmed reward of my pet "Dingo", thank for helping me to find it!. Please review reward arrived to your snowflake.
3) I have fixed lint error in my local. I have to submit the Pull Request again, but not in this moment (workin' on). Hope during the day.
;->

**Comment by jzafrap** [comment]
I already have submitted lint-cleaned code. ;->

**Pull request merged**
